ALTER TABLE IF EXISTS orders
ADD COLUMN IF NOT EXISTS delivery_status VARCHAR(30) DEFAULT 'ORDERED',
ADD COLUMN IF NOT EXISTS courier VARCHAR(100),
ADD COLUMN IF NOT EXISTS courier_code VARCHAR(50),
ADD COLUMN IF NOT EXISTS tracking_number VARCHAR(100),
ADD COLUMN IF NOT EXISTS shipped_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS delivered_at TIMESTAMP;
