ALTER TABLE IF EXISTS funding_documents
ADD COLUMN IF NOT EXISTS ocr_status VARCHAR(30),
ADD COLUMN IF NOT EXISTS ocr_result JSONB,
ADD COLUMN IF NOT EXISTS ocr_summary TEXT,
ADD COLUMN IF NOT EXISTS ocr_extracted_fields JSONB,
ADD COLUMN IF NOT EXISTS ocr_processed_at TIMESTAMP;
