ALTER TABLE IF EXISTS brewery_auth
  ADD COLUMN IF NOT EXISTS ocr_status VARCHAR(30),
  ADD COLUMN IF NOT EXISTS ocr_result JSONB,
  ADD COLUMN IF NOT EXISTS ocr_summary JSONB,
  ADD COLUMN IF NOT EXISTS ocr_error TEXT,
  ADD COLUMN IF NOT EXISTS ocr_checked_at TIMESTAMP;
